sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t hhy/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true hhy/docker-react-app npm run test -- --coverage


deploy:
  probider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-test"
  env: "Dockerreacttest-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-665683613775"
  bucket_path: docker-react-app
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key_id: $AWS_SECRET_ACCESS_KEY