sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t hhy/docker-react-app -f Dockerfile.dev

script:
  - docker run -e CI=true hhy/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"